### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by aboFaisal** [balena-io-playground/internetspeedtest#24]
I deplyed it in my Raspberry Pi 5 using belana, but the graph didn't show any data. and When I checked speedtest service log in belana I found the following:

```
speedtest  Traceback (most recent call last):
speedtest    File "./speedtest.py", line 5, in <module>
speedtest      import paho.mqtt.client as mqtt
speedtest    File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 51, in <module>
speedtest      from typing_extensions import Literal  # type: ignore
speedtest  ModuleNotFoundError: No module named 'typing_extensions'
speedtest  OKTraceback (most recent call last):
speedtest    File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 49, in <module>
speedtest      from typing import Literal
speedtest  ImportError: cannot import name 'Literal' from 'typing' (/usr/local/lib/python3.7/typing.py)
speedtest  
speedtest  During handling of the above exception, another exception occurred:
speedtest  
speedtest  Traceback (most recent call last):
speedtest    File "./speedtest.py", line 5, in <module>
speedtest      import paho.mqtt.client as mqtt
speedtest    File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 51, in <module>
speedtest      from typing_extensions import Literal  # type: ignore
speedtest  ModuleNotFoundError: No module named 'typing_extensions'
speedtest  OKTraceback (most recent call last):
speedtest    File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 49, in <module>
speedtest      from typing import Literal
speedtest  ImportError: cannot import name 'Literal' from 'typing' (/usr/local/lib/python3.7/typing.py)
speedtest  
speedtest  During handling of the above exception, another exception occurred:
speedtest  
speedtest  Traceback (most recent call last):
speedtest    File "./speedtest.py", line 5, in <module>
speedtest      import paho.mqtt.client as mqtt
speedtest    File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 51, in <module>
speedtest      from typing_extensions import Literal  # type: ignore
speedtest  ModuleNotFoundError: No module named 'typing_extensions'
speedtest  OKTraceback (most recent call last):
speedtest    File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 49, in <module>
speedtest  OKTraceback (most recent call last):
speedtest    File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 49, in <module>
speedtest      from typing import Literal
speedtest  ImportError: cannot import name 'Literal' from 'typing' (/usr/local/lib/python3.7/typing.py)
speedtest  
speedtest  During handling of the above exception, another exception occurred:
speedtest  
speedtest  Traceback (most recent call last):
speedtest    File "./speedtest.py", line 5, in <module>
speedtest      import paho.mqtt.client as mqtt
speedtest    File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 51, in <module>
speedtest      from typing_extensions import Literal  # type: ignore
speedtest  ModuleNotFoundError: No module named 'typing_extensions'

```

**Comment by phil-d-wilson** [comment]
Hey @aboFaisal 

It looks like Paho MQTT bumped by a major version which included some breaking changes: https://eclipse.dev/paho/files/paho.mqtt.python/html/changelog.html

And the version wasn't pinned in this project. I'll pin it to version 1.6.1 for now since I can't spot a super urgent reason to use the latest (i.e. no security issues) and the migration to 2.0 looks like it might take a while (PRs welcome).

I'm on it.

**Comment by phil-d-wilson** [comment]
Pinning to 1.6.1 gets this project working again - so I'll PR that change now.

**Comment by oriolpiera** [comment]
@phil-d-wilson this Issue and PR are still open, so current release still has a bug. 
How we can use this version of Dockerfile from Balena?

**Comment by phil-d-wilson** [comment]
@oriolpiera sorry man - I completely dropped the ball here. This is why people like me shouldn't meddle with code - they get distracted easily. I should stick to spreadsheets and board meetings. 🙄 

All done
